ARG BASE_ALPINE_IMAGE
FROM $BASE_ALPINE_IMAGE

# 最小化提供http服务的nginx
ENV NGINX_VERSION 1.14.2
ENV INSTALL_DIR "/usr/local/web/nginx"

COPY nginx "/etc/service/nginx"

RUN chmod +x /etc/service/nginx/run \
    && chmod +x /etc/service/nginx/log/run \
    # 安装nginx
    && GPG_KEYS=B0F4253373F8F6F510D42178520A9993A1C052F8 \
    && mkdir -p "$INSTALL_DIR" \
	&& CONFIG="\
		--prefix=$INSTALL_DIR \
		--conf-path=$INSTALL_DIR/conf/nginx.conf \
		--error-log-path=/var/log/nginx/error.log \
		--http-log-path=/var/log/nginx/access.log \
		--pid-path=/var/run/nginx.pid \
		--lock-path=/var/run/nginx.lock \
		--http-client-body-temp-path=/var/cache/nginx/client_temp \
		--http-proxy-temp-path=/var/cache/nginx/proxy_temp \
		--http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
		--user=nginx \
		--group=nginx \
		--with-http_ssl_module \
		--with-stream \
	" \
	&& addgroup -S nginx \
	&& adduser -D -S -h /var/cache/nginx -s /sbin/nologin -G nginx nginx \
	&& apk add --no-cache --virtual .build-deps \
		gcc \
		libc-dev \
		make \
		openssl-dev \
		pcre-dev \
		zlib-dev \
		linux-headers \
		curl \
		gnupg1 \
	&& curl -fSL https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz -o nginx.tar.gz \
	&& curl -fSL https://nginx.org/download/nginx-$NGINX_VERSION.tar.gz.asc  -o nginx.tar.gz.asc \
	&& export GNUPGHOME="$(mktemp -d)" \
	&& rm -rf "$GNUPGHOME" nginx.tar.gz.asc \
	&& mkdir -p /usr/src \
	&& tar -zxC /usr/src -f nginx.tar.gz \
	&& rm nginx.tar.gz \
	&& cd /usr/src/nginx-$NGINX_VERSION \
	&& ./configure $CONFIG --with-debug \
	&& make -j$(getconf _NPROCESSORS_ONLN) \
	&& ./configure $CONFIG \
	&& make -j$(getconf _NPROCESSORS_ONLN) \
	&& make install \
	&& rm -rf /etc/nginx/html/ \
	&& mkdir "$INSTALL_DIR/conf/conf.d/" \
	&& mkdir -p /usr/share/nginx/html/ \
	&& ln -s "$INSTALL_DIR/sbin/nginx" /usr/sbin/nginx \
	&& strip /usr/sbin/nginx* \
	&& rm -rf /usr/src/nginx-$NGINX_VERSION \
	\
	# Bring in gettext so we can get `envsubst`, then throw
	# the rest away. To do this, we need to install `gettext`
	# then move `envsubst` out of the way so `gettext` can
	# be deleted completely, then move `envsubst` back.
	&& apk add --no-cache --virtual .gettext gettext \
	&& mv /usr/bin/envsubst /tmp/ \
	\
	&& runDeps="$( \
		scanelf --needed --nobanner --format '%n#p' /usr/sbin/nginx /usr/lib/nginx/modules/*.so /tmp/envsubst \
			| tr ',' '\n' \
			| sort -u \
			| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
	)" \
	&& apk add --no-cache --virtual .nginx-rundeps $runDeps \
	&& apk del .build-deps \
	&& apk del .gettext \
	&& mv /tmp/envsubst /usr/local/bin/

COPY nginx-conf/nginx.conf "$INSTALL_DIR/conf/nginx.conf"
COPY nginx-conf/conf.d/server.conf "$INSTALL_DIR/conf/conf.d/server.conf"

EXPOSE 80

CMD ["runsvdir", "-P", "/etc/service"]
