version: '3'

# 构建php镜像

services:
  php:
    build:
      context: ${PHP_BUILD_CONTEXT}
      dockerfile: Dockerfile
      args:
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTPS_PROXY}
        no_proxy: ${NO_PROXY}
    image: ${PHP_BUILD_IMAGE}
    container_name: php
    restart: always
networks:
  default:
    external:
      name: host




